// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shkodran_Hasani_Zgjedhjet_API.Data;

#nullable disable

namespace Shkodran_Hasani_Zgjedhjet_API.Migrations
{
    [DbContext(typeof(LifeDbContext))]
    partial class LifeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shkodran_Hasani_Zgjedhjet_API.Models.Entities.Zgjedhjet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kategoria")
                        .HasColumnType("int");

                    b.Property<int>("Komuna")
                        .HasColumnType("int");

                    b.Property<int>("Partia")
                        .HasColumnType("int");

                    b.Property<string>("QendraVotimit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VendVotimi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Vota")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Zgjedhjet");
                });
#pragma warning restore 612, 618
        }
    }
}
